spring.application.name=auth-lib

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Auth API Configuration
auth-api.jwtSecret=your-secret-key-change-this-in-production-environment
auth-api.jwtExpirationMs=3600000
auth-api.refreshTokenExpirationMs=604800000
auth-api.baseEndpoint=/api/auth
auth-api.signinEndpoint=/signin
auth-api.signupEndpoint=/signup
auth-api.refreshEndpoint=/refresh
auth-api.verifyEndpoint=/verify
auth-api.forgotPasswordEndpoint=/forgot-password
auth-api.resetPasswordEndpoint=/reset-password


# Local Email setup
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.username=sentinal@auth.com
spring.mail.password=sentinal@auth
